# Generated by Django 5.0 on 2024-09-11 10:00

from django.db import migrations, models


def insert_required_settings(apps, schema_editor):
    AppSetting = apps.get_model("stats", "AppSettting")

    AppSetting.objects.create(key="total_prize_amount", value="13$", is_public=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=1000, unique=True)),
                ("value", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            insert_required_settings, reverse_code=migrations.RunPython.noop
        ),
    ]
