# Generated by Django 5.0 on 2024-08-15 09:27

import core.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_profile', models.PositiveBigIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('prize_amount', core.fields.BigNumField(max_length=200)),
                ('chain_id', models.IntegerField()),
                ('token', models.CharField(max_length=100)),
                ('token_address', models.CharField(max_length=255)),
                ('discord_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email_url', models.EmailField(max_length=255)),
                ('telegram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('token_image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('winner_count', models.IntegerField(default=0)),
                ('amount_won', core.fields.BigNumField(default=0, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', core.fields.CloudflareImagesField(blank=True, null=True, upload_to='', variant='public')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.competition')),
            ],
            options={
                'unique_together': {('competition', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_hinted_choice', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='quiz.sponsor'),
        ),
        migrations.CreateModel(
            name='UserCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('amount_won', core.fields.BigNumField(default=0, max_length=200)),
                ('is_hint_used', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.competition')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.apiuserprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'competition')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participated_competitions', through='quiz.UserCompetition', to='authentication.apiuserprofile'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiz.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiz.choice')),
                ('user_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_answer', to='quiz.usercompetition')),
            ],
            options={
                'unique_together': {('user_competition', 'question')},
            },
        ),
    ]
