# Generated by Django 5.0 on 2024-08-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile'),
        ('quiz', '0003_alter_competition_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(related_name='participated_competitions', through='quiz.UserCompetition', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='user_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='usercompetition',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
