# Generated by Django 5.0 on 2024-08-27 09:22

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_competition_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='amount_won',
            field=core.fields.BigNumField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='competition',
            name='winner_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
