# Generated by Django 5.0 on 2024-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_competition_shuffle_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='prize_amount',
            field=models.FloatField(),
        ),
    ]
