# Generated by Django 5.0 on 2024-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_competition_shuffle_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='token_decimals',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
