# Generated by Django 5.0 on 2024-09-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_competition_token_decimals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='amount_won',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='winner_count',
        ),
        migrations.AddField(
            model_name='competition',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
