# Generated by Django 5.0 on 2024-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_competition_amount_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='split_prize',
            field=models.BooleanField(default=True),
        ),
    ]
