services:
  backend:
    build: .
    command: python manage.py runserver
    environment:
      - FIELD_KEY=${FIELD_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - MEMCACHEDCLOUD_SERVERS=memcached:11211
    expose:
      - 4444
    ports:
      - "4444:4444"
    depends_on:
      - database
      - redis
    volumes:
      - ./src/:/usr/src/app

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    platform: linux/amd64
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
volumes:
  db:
    driver: local
  cache:
    driver: local
