# Generated by Django 4.0.4 on 2024-04-04 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def raise_migrations_not_allowed(apps, schema_editor):
    raise NotImplementedError()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(raise_migrations_not_allowed)
    ]
