# Generated by Django 5.0 on 2024-08-23 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username can only contain letters, digits and @/./+/-/_.",
                                regex="^[\\w.@+-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
            ],
        ),
    ]
