# Generated by Django 5.0 on 2024-08-29 09:39

import cloudflare_images.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_create_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=cloudflare_images.field.CloudflareImagesField(blank=True, null=True, upload_to='', variant='public'),
        ),
    ]
