# Generated by Django 5.0 on 2024-09-07 12:44

import authentication.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(authentication.models.Lower('wallet_address'), name='unique_wallet_address_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(authentication.models.Lower('username'), name='unique_username_case_insensitive'),
        ),
    ]
